## Python ile Veri Analizi

Bu süreçte ele alınacak konular:

- NumPy (Matematik)
- Pandas (Veri Analizi)
- Veri Görselleştirme: Matplotlib & Seaborn 
- Gelişmiş Fonksiyonel Keşifci Veri Analizi

In [2]:
import numpy as np

a = [1, 2, 3, 4]
b = [2, 3, 4 ,5]
ab = []

for i in range (0, len(a)):
    ab.append(a[i]*b[i])
print(ab)



[2, 6, 12, 20]


In [7]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4 ,5])

print(a*b)

np.zeros(10, dtype = int )
np.random.randint(1,10,10)
np.random.normal(10, 4 ,(3, 4))

[ 2  6 12 20]


array([[ 7.41281128,  4.29960715,  4.81978887, 11.12936353],
       [ 6.22642428, 10.975536  ,  7.80510326,  8.22965112],
       [ 5.53334952, 11.35421174,  8.23019735,  8.14676513]])

In [12]:
x = np.random.randint(10, size = 5)
print(x)

# ndim  --> boyut sayısı
# shape --> boyut bilgisi
# size  --> toplam eleman sayısı
# dtype --> array veri tipi

print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

[7 9 6 8 3]
1
(5,)
5
int32


In [27]:
y = np.random.randint(10, size = 9)
print(y)

print("------")

y = y.reshape(3, 3)
print(y)

print("------")

z = np.random.randint(10, size = 9).reshape(3,3)
print(z)

[6 0 1 6 9 9 1 7 3]
------
[[6 0 1]
 [6 9 9]
 [1 7 3]]
------
[[6 1 9]
 [9 0 8]
 [9 3 1]]


In [38]:
v = np.arange(0,42,6)  # e  kadar

print(v)

# Fancy Index

vvv = [1, 2, 3, 6]
vv = v[vvv]

print(vv)

print(v < 13)

print(v[v < 13])

[ 0  6 12 18 24 30 36]
[ 6 12 18 36]
[ True  True  True False False False False]
[ 0  6 12]


In [40]:
# 5x + 3y = 14
# 3x + y = 6

a = np.array([[5,3],[3,1]])
b = np.array([14, 6])

print(np.linalg.solve(a, b))

[1. 3.]


In [42]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('1. boyuttaki 2.eleman: ', arr[0, 1])

1. boyuttaki 2.eleman:  2


In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])  

[5 6]


In [44]:
array = np.array([1, 2, 3, 4, 5, 6, 7])

filter_array = array % 2 == 0

new_array = array[filter_array]

print(new_array)

[2 4 6]


### Pandas

In [53]:
import pandas as pd

d = pd.Series(np.random.randint(1,50, size = 5))

print(d)
print(type(d), d.index, d.ndim, d.size, d.dtype)
print(d.values)
print(d.head(3))
print(d.tail(3))

0    13
1    19
2    23
3    20
4    19
dtype: int32
<class 'pandas.core.series.Series'> RangeIndex(start=0, stop=5, step=1) 1 5 int32
[13 19 23 20 19]
0    13
1    19
2    23
dtype: int32
2    23
3    20
4    19
dtype: int32


In [57]:
# Pandas ile veri okuma

df = pd.read_excel("luxury_cosmetics_fraud_analysis_2025.xlsx")
print(df.head(3))

                         Transaction_ID                           Customer_ID  \
0  702bdd9b-9c93-41e3-9dbb-a849b2422080  119dca0b-8554-4b2d-9bec-e964eaf6af97   
1  2e64c346-36bc-4acf-bc2b-8b0fdf46abc5  299df086-26c4-4708-b6d7-fcaeceb14637   
2  29ad1278-70ce-421f-8d81-23816b39f4ac  dfa3d24d-b935-49a5-aa1d-7d57a44d8773   

  Transaction_Date Transaction_Time  Customer_Age Customer_Loyalty_Tier  \
0       2025-07-27         04:04:15          56.0                Silver   
1       2025-03-14         20:23:23          46.0              Platinum   
2       2025-02-20         12:36:02          32.0                Silver   

        Location           Store_ID       Product_SKU Product_Category  \
0  San Francisco        FLAGSHIP-LA   NEBULA-SERUM-07        Concealer   
1         Zurich  BOUTIQUE-SHANGHAI  STELLAR-FOUND-03         Lipstick   
2          Milan        POPUP-TOKYO    SOLAR-BLUSH-04          Mascara   

   Purchase_Amount  Payment_Method Device_Type      IP_Address  Fraud_Flag  \